


 ----------------------------------------------------------------------------------------------------------

#  Réalisez une étude de santé publique

Cette étude a pour but de rechercher les causes des faims dans le monde en 2013.

FAO: FOOD AND AGRICULTURE ORGANISATION OF THE UNITED NATIONS (institution spécialisée des Nations Unies, pour l'alimentation,
dans son sens le plus large, qui inclue notament l'agriculture, les forêts, les pêches et les industries se rattachant directement à l'alimentation.

In [90]:
# importation des librairies 
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [91]:
# importations des fichiers
franimaux = pd.read_csv('fr_animaux.csv')
frvegetaux = pd.read_csv('fr_vegetaux.csv')
frcéréales = pd.read_csv('fr_céréales.csv')
frpopulation = pd.read_csv('fr_population.csv')
frsousalimentation = pd.read_csv('fr_sousalimentation.csv')
franimaux.head()

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
0,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5511,Production,2731,Viande de Bovins,2013,2013,Milliers de tonnes,134.00,S,Données standardisées
1,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5611,Importations - Quantité,2731,Viande de Bovins,2013,2013,Milliers de tonnes,6.00,S,Données standardisées
2,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5301,Disponibilité intérieure,2731,Viande de Bovins,2013,2013,Milliers de tonnes,140.00,S,Données standardisées
3,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5142,Nourriture,2731,Viande de Bovins,2013,2013,Milliers de tonnes,140.00,S,Données standardisées
4,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,645,Disponibilité alimentaire en quantité (kg/pers...,2731,Viande de Bovins,2013,2013,kg,4.59,Fc,Donnée calculée

In [92]:
frvegetaux.head()

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
0,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5511,Production,2511,Blé,2013,2013,Milliers de tonnes,5169.0,S,Données standardisées
1,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5611,Importations - Quantité,2511,Blé,2013,2013,Milliers de tonnes,1173.0,S,Données standardisées
2,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5072,Variation de stock,2511,Blé,2013,2013,Milliers de tonnes,-350.0,S,Données standardisées
3,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5301,Disponibilité intérieure,2511,Blé,2013,2013,Milliers de tonnes,5992.0,S,Données standardisées
4,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5527,Semences,2511,Blé,2013,2013,Milliers de tonnes,322.0,S,Données standardisées

In [93]:
frcéréales.head()

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
0,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5511,Production,2511,Blé,2013,2013,Milliers de tonnes,5169,S,Données standardisées
1,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5511,Production,2805,Riz (Eq Blanchi),2013,2013,Milliers de tonnes,342,S,Données standardisées
2,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5511,Production,2513,Orge,2013,2013,Milliers de tonnes,514,S,Données standardisées
3,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5511,Production,2514,Maïs,2013,2013,Milliers de tonnes,312,S,Données standardisées
4,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5511,Production,2517,Millet,2013,2013,Milliers de tonnes,13,S,Données standardisées

In [94]:
frpopulation.head()

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
0,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,511,Population totale,2501,Population,2013,2013,1000 personnes,30552,NaN,Donnée officielle
1,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,202,Afrique du Sud,511,Population totale,2501,Population,2013,2013,1000 personnes,52776,NaN,Donnée officielle
2,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,3,Albanie,511,Population totale,2501,Population,2013,2013,1000 personnes,3173,NaN,Donnée officielle
3,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,4,Algérie,511,Population totale,2501,Population,2013,2013,1000 personnes,39208,NaN,Donnée officielle
4,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,79,Allemagne,511,Population totale,2501,Population,2013,2013,1000 personnes,82727,NaN,Donnée officielle

In [95]:
frsousalimentation.head()

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
0,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20122014,2012-2014,millions,7.9,F,Estimation FAO,NaN
1,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20132015,2013-2015,millions,8.8,F,Estimation FAO,NaN
2,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20142016,2014-2016,millions,9.6,F,Estimation FAO,NaN
3,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20152017,2015-2017,millions,10.2,F,Estimation FAO,NaN
4,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20162018,2016-2018,millions,10.6,F,Estimation FAO,NaN

les 3 premières questions c'est : Calculez le nombre total d’humains sur la planète, Identifiez les redondances, Calculez (pour chaque pays et chaque produit) la disponibilité alimentaire en kcal puis en kg de protéines.

# Nettoyage des données

Nettoyage pour df_frpopulation

In [96]:
# sélection des colonnes pertinentes pour population et qui nous intéressent pour faire le calcul
population_2013 = frpopulation[['Zone','Code zone','Année','Valeur','Unité']].copy()
population_2013.rename(columns={'Code zone':'code_pays','Zone':'pays','Année':'annee', 'Unité':'unite','Valeur':'population', }, inplace=True)
population_2013.head()

             pays  code_pays  annee  population           unite
0     Afghanistan          2   2013       30552  1000 personnes
1  Afrique du Sud        202   2013       52776  1000 personnes
2         Albanie          3   2013        3173  1000 personnes
3         Algérie          4   2013       39208  1000 personnes
4       Allemagne         79   2013       82727  1000 personnes

In [97]:
#la clé primaire de ma df est code_pays et je dois vérifie que je ne pas de déplication sur mon code pays
population_2013.duplicated('code_pays').sum()

0

In [98]:
#isna Pour détecter les NaN valeurs c'est pour vérifier ya des valeurs manquante
population_2013.isna().sum()

pays          0
code_pays     0
annee         0
population    0
unite         0
dtype: int64

In [99]:
# connaitre le typage de chaque variable du tableau
population_2013.dtypes

pays          object
code_pays      int64
annee          int64
population     int64
unite         object
dtype: object

In [100]:
#retourne les valeurs uniques dans la série Python Pandas. Les valeurs sont classées par apparence.
#La fonction Python Numpy.unique() récupère toutes les valeurs uniques dans le tableau donné et trie ces valeurs uniques.
population_2013['pays'].unique()

array(['Afghanistan', 'Afrique du Sud', 'Albanie', 'Algérie', 'Allemagne',
       'Angola', 'Antigua-et-Barbuda', 'Arabie saoudite', 'Argentine',
       'Arménie', 'Australie', 'Autriche', 'Azerbaïdjan', 'Bahamas',
       'Bangladesh', 'Barbade', 'Bélarus', 'Belgique', 'Belize', 'Bénin',
       'Bermudes', 'Bolivie (État plurinational de)',
       'Bosnie-Herzégovine', 'Botswana', 'Brésil', 'Brunéi Darussalam',
       'Bulgarie', 'Burkina Faso', 'Cabo Verde', 'Cambodge', 'Cameroun',
       'Canada', 'Chili', 'Chine', 'Chine - RAS de Hong-Kong',
       'Chine - RAS de Macao', 'Chine, continentale',
       'Chine, Taiwan Province de', 'Chypre', 'Colombie', 'Congo',
       'Costa Rica', "Côte d'Ivoire", 'Croatie', 'Cuba', 'Danemark',
       'Djibouti', 'Dominique', 'Égypte', 'El Salvador',
       'Émirats arabes unis', 'Équateur', 'Espagne', 'Estonie',
       'Eswatini', "États-Unis d'Amérique", 'Éthiopie',
       'Fédération de Russie', 'Fidji', 'Finlande', 'France', 'Gabon',
       'Gambie', 'Géorgie', 'Ghana', 'Grèce', 'Grenade', 'Guatemala',
       'Guinée', 'Guinée-Bissau', 'Guyana', 'Haïti', 'Honduras',
       'Hongrie', 'Îles Salomon', 'Inde', 'Indonésie',
       "Iran (République islamique d')", 'Iraq', 'Irlande', 'Islande',
       'Israël', 'Italie', 'Jamaïque', 'Japon', 'Jordanie', 'Kazakhstan',
       'Kenya', 'Kirghizistan', 'Kiribati', 'Koweït', 'Lesotho',
       'Lettonie', 'Liban', 'Libéria', 'Lituanie', 'Luxembourg',
       'Macédoine du Nord', 'Madagascar', 'Malaisie', 'Malawi',
       'Maldives', 'Mali', 'Malte', 'Maroc', 'Maurice', 'Mauritanie',
       'Mexique', 'Mongolie', 'Monténégro', 'Mozambique', 'Myanmar',
       'Namibie', 'Népal', 'Nicaragua', 'Niger', 'Nigéria', 'Norvège',
       'Nouvelle-Calédonie', 'Nouvelle-Zélande', 'Oman', 'Ouganda',
       'Ouzbékistan', 'Pakistan', 'Panama', 'Paraguay', 'Pays-Bas',
       'Pérou', 'Philippines', 'Pologne', 'Polynésie française',
       'Portugal', 'République centrafricaine', 'République de Corée',
       'République de Moldova', 'République démocratique populaire lao',
       'République dominicaine',
       'République populaire démocratique de Corée',
       'République-Unie de Tanzanie', 'Roumanie', 'Royaume-Uni', 'Rwanda',
       'Sainte-Lucie', 'Saint-Kitts-et-Nevis',
       'Saint-Vincent-et-les Grenadines', 'Samoa', 'Sao Tomé-et-Principe',
       'Sénégal', 'Serbie', 'Sierra Leone', 'Slovaquie', 'Slovénie',
       'Soudan', 'Sri Lanka', 'Suède', 'Suisse', 'Suriname',
       'Tadjikistan', 'Tchad', 'Tchéquie (la)', 'Thaïlande',
       'Timor-Leste', 'Togo', 'Trinité-et-Tobago', 'Tunisie',
       'Turkménistan', 'Turquie', 'Ukraine', 'Uruguay', 'Vanuatu',
       'Venezuela (République bolivarienne du)', 'Viet Nam', 'Yémen',
       'Zambie', 'Zimbabwe'], dtype=object)

In [101]:
#Il y avait une redondance sur la Chine : le pays est comme compté 2 fois : une fois en général ("Chine") et une autre fois en province. 
#Je décide donc de supprimer la Chine en général et de garder les provinces car cela est plus précis pour l'analyse.
population_2013.drop(population_2013[population_2013['pays'].str.startswith("Chine,") == True].index, inplace=True)
population_2013.drop(population_2013[population_2013['pays'].str.startswith("Chine -") == True].index, inplace=True)

In [102]:
population = population_2013

Nettoyage des données liées aux aliments

In [103]:
"""On commence par créer une colonne origine aux Dataframes animaux et végétaux pour s'y retrouver dans le nouveau Df concaténer.
   La concaténation des 2 Dfs s'explique car nous avons besoin de chaque produits, donc animal et végétal. Cela dit, céréales étant
   un sous-ensemble de df_végétaux, on peut s'en passer."""

frvegetaux['origine'] = 'vegetal'# On place des nouvelles colonnes qui indique l'origine des produits.
franimaux['origine'] = 'animal'

fr_alim = pd.concat([franimaux,frvegetaux]).copy()

fr_alim.rename(columns = {"Code zone":"code_pays",
                                  "Zone":"pays",
                                  "Année":"annee",
                                  "Unité":"unite",
                                  "Valeur" :"valeur"},inplace = True)

# On drop les provinces de Chine afin d'avoir un merge cohérent
fr_alim.drop(fr_alim[fr_alim['pays'].str.startswith("Chine,") == True].index, inplace=True)
fr_alim.drop(fr_alim[fr_alim['pays'].str.startswith("Chine -") == True].index, inplace=True)

# On pivot sur Element afin d'avoir un DataFrame plus lisible et plus compréhensible ici ainsi que pour la suite des questions.

fr_alim = fr_alim.pivot_table(index=['code_pays','pays','Code Produit','Produit', 'origine'], values='valeur', columns='Élément')

fr_alim.head()

Élément                                         Aliments pour animaux  \
code_pays pays    Code Produit Produit origine
1         Arménie 2511         Blé     vegetal                   93.0
                  2513         Orge    vegetal                  137.0
                  2514         Maïs    vegetal                   96.0
                  2515         Seigle  vegetal                    1.0
                  2516         Avoine  vegetal                    4.0

Élément                                         Autres utilisations (non alimentaire)  \
code_pays pays    Code Produit Produit origine
1         Arménie 2511         Blé     vegetal                                    0.0
                  2513         Orge    vegetal                                   26.0
                  2514         Maïs    vegetal                                    NaN
                  2515         Seigle  vegetal                                    NaN
                  2516         Avoine  vegetal                                    NaN

Élément                                         Disponibilité alimentaire (Kcal/personne/jour)  \
code_pays pays    Code Produit Produit origine
1         Arménie 2511         Blé     vegetal                                          1024.0
                  2513         Orge    vegetal                                             0.0
                  2514         Maïs    vegetal                                             0.0
                  2515         Seigle  vegetal                                             1.0
                  2516         Avoine  vegetal                                             2.0

Élément                                         Disponibilité alimentaire en quantité (kg/personne/an)  \
code_pays pays    Code Produit Produit origine
1         Arménie 2511         Blé     vegetal                                             130.60
                  2513         Orge    vegetal                                               0.00
                  2514         Maïs    vegetal                                               0.03
                  2515         Seigle  vegetal                                               0.12
                  2516         Avoine  vegetal                                               0.37

Élément                                         Disponibilité de matière grasse en quantité (g/personne/jour)  \
code_pays pays    Code Produit Produit origine
1         Arménie 2511         Blé     vegetal                                               3.60
                  2513         Orge    vegetal                                               0.00
                  2514         Maïs    vegetal                                                NaN
                  2515         Seigle  vegetal                                               0.00
                  2516         Avoine  vegetal                                               0.03

Élément                                         Disponibilité de protéines en quantité (g/personne/jour)  \
code_pays pays    Code Produit Produit origine
1         Arménie 2511         Blé     vegetal                                              30.52
                  2513         Orge    vegetal                                               0.00
                  2514         Maïs    vegetal                                               0.01
                  2515         Seigle  vegetal                                               0.02
                  2516         Avoine  vegetal                                               0.09

Élément                                         Disponibilité intérieure  \
code_pays pays    Code Produit Produit origine
1         Arménie 2511         Blé     vegetal                     554.0
                  2513         Orge    vegetal                     198.0
                  2514         Maïs    vegetal                     102.0
                  2515         Seigle  vegetal                       1.0
                  2516         Avoine  vegetal                       6.0

Élément                                         Exportations - Quantité  \
code_pays pays    Code Produit Produit origine
1         Arménie 2511         Blé     vegetal                      1.0
                  2513         Orge    vegetal                      0.0
                  2514         Maïs    vegetal                      NaN
                  2515         Seigle  vegetal                      NaN
                  2516         Avoine  vegetal                      NaN

Élément                                         Importations - Quantité  \
code_pays pays    Code Produit Produit origine
1         Arménie 2511         Blé     vegetal                    361.0
                  2513         Orge    vegetal                      9.0
                  2514         Maïs    vegetal                     82.0
                  2515         Seigle  vegetal                      0.0
                  2516         Avoine  vegetal                      1.0

Élément                                         Nourriture  Pertes  \
code_pays pays    Code Produit Produit origine
1         Arménie 2511         Blé     vegetal       389.0    32.0
                  2513         Orge    vegetal         0.0    15.0
                  2514         Maïs    vegetal         0.0     7.0
                  2515         Seigle  vegetal         0.0     0.0
                  2516         Avoine  vegetal         1.0     0.0

Élément                                         Production  Semences  \
code_pays pays    Code Produit Produit origine
1         Arménie 2511         Blé     vegetal       312.0      30.0
                  2513         Orge    vegetal       189.0      14.0
                  2514         Maïs    vegetal        21.0       0.0
                  2515         Seigle  vegetal         1.0       0.0
                  2516         Avoine  vegetal         5.0       0.0

Élément                                         Traitement  Variation de stock
code_pays pays    Code Produit Produit origine
1         Arménie 2511         Blé     vegetal        10.0              -118.0
                  2513         Orge    vegetal         7.0                 0.0
                  2514         Maïs    vegetal         NaN                 NaN
                  2515         Seigle  vegetal         NaN                 0.0
                  2516         Avoine  vegetal         NaN                 NaN

In [104]:
# Reset les index pour pas les dupliquer et rename_axis pour éviter que les noms de colonnes soient au dessus des autres.

fr_alim.rename_axis(None,axis=1)
fr_alim.reset_index(inplace= True)
fr_alim.head()

Élément,code_pays,pays,Code Produit,Produit,origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock
0,1,Arménie,2511,Blé,vegetal,93.0,0.0,1024.0,130.60,3.60,30.52,554.0,1.0,361.0,389.0,32.0,312.0,30.0,10.0,-118.0
1,1,Arménie,2513,Orge,vegetal,137.0,26.0,0.0,0.00,0.00,0.00,198.0,0.0,9.0,0.0,15.0,189.0,14.0,7.0,0.0
2,1,Arménie,2514,Maïs,vegetal,96.0,NaN,0.0,0.03,NaN,0.01,102.0,NaN,82.0,0.0,7.0,21.0,0.0,NaN,NaN
3,1,Arménie,2515,Seigle,vegetal,1.0,NaN,1.0,0.12,0.00,0.02,1.0,NaN,0.0,0.0,0.0,1.0,0.0,NaN,0.0
4,1,Arménie,2516,Avoine,vegetal,4.0,NaN,2.0,0.37,0.03,0.09,6.0,NaN,1.0,1.0,0.0,5.0,0.0,NaN,NaN

In [105]:
#Merge sur population afin d'avoir toutes les informations sur le nombre d'habitants par pays.

fr_alim = pd.merge(fr_alim,population,on= 'code_pays',how='left')

In [106]:
fr_alim.drop(columns= 'pays_y') # Eviter une seconde colonne à pays_x

,code_pays,pays_x,Code Produit,Produit,origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),...,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock,annee,population,unite
0,1,Arménie,2511,Blé,vegetal,93.0,0.0,1024.0,130.60,3.60,...,361.0,389.0,32.0,312.0,30.0,10.0,-118.0,2013,2977,1000 personnes
1,1,Arménie,2513,Orge,vegetal,137.0,26.0,0.0,0.00,0.00,...,9.0,0.0,15.0,189.0,14.0,7.0,0.0,2013,2977,1000 personnes
2,1,Arménie,2514,Maïs,vegetal,96.0,NaN,0.0,0.03,NaN,...,82.0,0.0,7.0,21.0,0.0,NaN,NaN,2013,2977,1000 personnes
3,1,Arménie,2515,Seigle,vegetal,1.0,NaN,1.0,0.12,0.00,...,0.0,0.0,0.0,1.0,0.0,NaN,0.0,2013,2977,1000 personnes
4,1,Arménie,2516,Avoine,vegetal,4.0,NaN,2.0,0.37,0.03,...,1.0,1.0,0.0,5.0,0.0,NaN,NaN,2013,2977,1000 personnes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14938,351,Chine,2781,Huiles de Poissons,animal,47.0,80.0,0.0,0.00,0.00,...,91.0,0.0,NaN,50.0,NaN,NaN,0.0,2013,1416667,1000 personnes
14939,351,Chine,2782,Huiles de Foie de Poisso,animal,0.0,0.0,0.0,0.00,0.00,...,1.0,0.0,NaN,0.0,NaN,NaN,0.0,2013,1416667,1000 personnes
14940,351,Chine,2805,Riz (Eq Blanchi),vegetal,12117.0,2085.0,797.0,77.45,2.68,...,2714.0,109725.0,6406.0,136873.0,4679.0,12.0,-3998.0,2013,1416667,1000 personnes
14941,351,Chine,2848,Lait - Excl Beurre,animal,1632.0,42.0,59.0,33.18,3.25,...,9780.0,47009.0,1433.0,40570.0,NaN,0.0,0.0,2013,1416667,1000 personnes
14942,351,Chine,2899,Miscellanees,vegetal,NaN,NaN,0.0,NaN,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013,1416667,1000 personnes

# Analyse Exploratoire de données
Créez un dataframe contenant les informations de population de chaque pays. Calculez le nombre total d’humains sur la planète. Critiquez votre résultat. En cas d’anomalie, analysez et effectuer les corrections nécessaires.

Question 1 : donnez le résultat de votre calcul pour l'année 2013.

In [107]:
# Formatage des données pour frpopulation

frpopulation["Zone"].values  # Il y a une redondance sur Chine, on supprime Chine et on garde les subdivisions.

# On supprime les doublons
frpopulation = frpopulation.drop_duplicates()

print("Il y a " + str(frpopulation["Valeur"].sum(skipna=True)*1000))

Il y a 8413993000

il y a une redondance ici

Après avoir sélectionnez les colonnes intéressantes , on fait une copie du DataFrame afin d'éviter de toucher le Df original(le laisser intacte), on enleve les redondances dans les lignes du Df puis on renomme les colonnes afin d'éviter les espaces qui ne sont pas souhaitable en programmation. On fait la somme de la colonne population et on s'aperçoit du nombre très élevé d'habitants en 2013 : actuellement la population est d'environ 7.53 milliard dans le monde, alors qu'ici le résultat affiche 8 millaird : regardons s'il n'y a pas une redondance quelque part.

In [108]:
# On supprime 'Chine' puis on recalcule le nombre total d'habitant sur Terre en 2013.

#population = population_2013[population_2013["pays"] != "Chine"]

population["pays"].unique() # Il ne reste que les provinces de Chine

print("Il y a en 2013: " + str(population["population"].sum(skipna = True)* 1000)+" " +"habitant sur Terre")

Il y a en 2013: 6997326000 habitant sur Terre

La population mondiale en 2013 considérée dans cette étude sera donc la suivante : 6,997,326,000 habitants

Il y avait une redondance sur la Chine : le pays est comme compté 2 fois : une fois en général ("Chine") et une autre fois en province. Je décide donc de supprimer la Chine en général et de garder les provinces car cela est plus précis pour l'analyse.

In [109]:
#On stocke la valeur de population multiplié par 1000 pour plus tard dans les questions

population_2013 = (population['population'] * 1000).sum()

-------------------------------------------------------------------------

Parmi les documents sur les Bilans alimentaires que vous avez téléchargés, il y a des informations redondantes. En effet, pour un pays donné, certaines de ces informations peuvent se calculer à partir d'autres :

Production,Importations,Exportations ,Variation de stock ,Disponibilité intérieure ,Semences ,Pertes,Nourriture(aussi appelée Disponibilité alimentaire),Aliments pour animaux ,Traitement,Autres utilisations.

Question 2 : Identifiez ces redondances, en donnant votre réponse sous forme de formule mathématique (pas besoin de coder ici ). C'est une équation à 3 termes de type (a_1 + a2 + [...] = b_1 + b_2 + [...] = c_1 + c_2 + [...]) ) faisant intervenir chacune des 11 quantités données ci dessus. Illustrez cette équation avec l'exemple du blé en France. Pour avoir un indice, cliquez sur "Définitions et Standards" sur la page de téléchargement des données.

In [110]:
frvegetaux = pd.read_csv('fr_vegetaux.csv')

frvegetaux.columns = frvegetaux.columns.str.strip().str.lower().str.replace(' ', '_')

frvegetaux.rename(columns={ 'valeur': 'quantite', 'élément': 'element'}, inplace=True)

# Supprimer les données agrégées des régions

frvegetaux.drop(frvegetaux[frvegetaux['code_zone']==351].index, inplace=True)

frvegetaux = frvegetaux[(frvegetaux.zone == 'France') & (frvegetaux.code_produit == 2511)]

frvegetaux.head()

,code_domaine,domaine,code_zone,zone,code_élément,element,code_produit,produit,code_année,année,unité,quantite,symbole,description_du_symbole
37487,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,68,France,5511,Production,2511,Blé,2013,2013,Milliers de tonnes,38614.0,S,Données standardisées
37488,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,68,France,5611,Importations - Quantité,2511,Blé,2013,2013,Milliers de tonnes,2055.0,S,Données standardisées
37489,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,68,France,5072,Variation de stock,2511,Blé,2013,2013,Milliers de tonnes,1131.0,S,Données standardisées
37490,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,68,France,5911,Exportations - Quantité,2511,Blé,2013,2013,Milliers de tonnes,21502.0,S,Données standardisées
37491,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,68,France,5301,Disponibilité intérieure,2511,Blé,2013,2013,Milliers de tonnes,20298.0,S,Données standardisées

In [111]:
#Illustrez cette équation avec l'exemple du blé en France.
frvegetaux.loc[(frvegetaux['zone']=='France')&(frvegetaux['element']=='Production')&(frvegetaux['produit']=='Blé'),:]

,code_domaine,domaine,code_zone,zone,code_élément,element,code_produit,produit,code_année,année,unité,quantite,symbole,description_du_symbole
37487,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,68,France,5511,Production,2511,Blé,2013,2013,Milliers de tonnes,38614.0,S,Données standardisées

In [112]:
#Question2 Liens entre production,importations, exportations, disponibilité intérieure et variations de stock
#Il semblerait que la disponibilité intérieure se calcule de la façon suivante :
#Dispo_interieur == (Production + Importation - Exportation  + Variation_stock) == (Nourriture + Nourriture_animaux + Semences + Pertes + Traitement + Autres_utilisations_non_alimentaire)

In [113]:
frvegetaux['element'].unique()

array(['Production', 'Importations - Quantité', 'Variation de stock',
       'Exportations - Quantité', 'Disponibilité intérieure',
       'Aliments pour animaux', 'Semences', 'Pertes', 'Traitement',
       'Autres utilisations (non alimentaire)', 'Nourriture',
       'Disponibilité alimentaire en quantité (kg/personne/an)',
       'Disponibilité alimentaire (Kcal/personne/jour)',
       'Disponibilité de protéines en quantité (g/personne/jour)',
       'Disponibilité de matière grasse en quantité (g/personne/jour)'],
      dtype=object)

In [114]:
Production = frvegetaux.loc[frvegetaux['element'] == 'Production'].sum()['quantite']*1000000
Importation = frvegetaux.loc[frvegetaux['element'] == 'Importations - Quantité'].sum()['quantite']*1000000
Exportation = frvegetaux.loc[frvegetaux['element'] == 'Exportations - Quantité'].sum()['quantite']*1000000
Variation_stock = frvegetaux.loc[frvegetaux['element'] == 'Variation de stock'].sum()['quantite']*1000000
Dispo_interieur = Production + Importation - Exportation  + Variation_stock
Dispo_interieur

20298000000.0

In [115]:
Nourriture = frvegetaux.loc[frvegetaux['element'] == 'Nourriture'].sum()['quantite']*1000000
Nourriture_animaux = frvegetaux.loc[frvegetaux['element'] == 'Aliments pour animaux'].sum()['quantite']*1000000
Semences = frvegetaux.loc[frvegetaux['element'] == 'Semences'].sum()['quantite']*1000000
Pertes = frvegetaux.loc[frvegetaux['element'] == 'Pertes'].sum()['quantite']*1000000
Traitement = frvegetaux.loc[frvegetaux['element'] == 'Traitement'].sum()['quantite']*1000000
Autres_utilisations_non_alimentaire = frvegetaux.loc[frvegetaux['element'] == 'Autres utilisations (non alimentaire)'].sum()['quantite']*1000000
Dispo_interieur = Nourriture + Nourriture_animaux + Semences + Pertes + Traitement + Autres_utilisations_non_alimentaire
Dispo_interieur

20298000000.0

In [116]:
Dispo_interieur == (Production + Importation - Exportation  + Variation_stock) == (Nourriture + Nourriture_animaux + Semences + Pertes + Traitement + Autres_utilisations_non_alimentaire)

True

Disponibilité intérieure est donc la redondance qui se retrouve parmis les 11 quantités données

-------------------------------------------------------------------------------------------------

Question 3 : Calculez (pour chaque pays et chaque produit) la disponibilité alimentaire en kcal puis en kg de protéines.

Vous ferez cela à partir de ces informations :

Population de chaque pays ; Disponibilité alimentaire donnée pour chaque produit et pour chaque pays en kcal/personne/jour. Disponibilité alimentaire en protéines donnée pour chaque produit et pour chaque pays en g/personne/jour.

In [117]:
#calcul(pour chaque pays et chaque produit) la disponibilité alimentaire en kcal puis en kg de protéines.
fr_alim.head()

,code_pays,pays_x,Code Produit,Produit,origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),...,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock,pays_y,annee,population,unite
0,1,Arménie,2511,Blé,vegetal,93.0,0.0,1024.0,130.60,3.60,...,389.0,32.0,312.0,30.0,10.0,-118.0,Arménie,2013,2977,1000 personnes
1,1,Arménie,2513,Orge,vegetal,137.0,26.0,0.0,0.00,0.00,...,0.0,15.0,189.0,14.0,7.0,0.0,Arménie,2013,2977,1000 personnes
2,1,Arménie,2514,Maïs,vegetal,96.0,NaN,0.0,0.03,NaN,...,0.0,7.0,21.0,0.0,NaN,NaN,Arménie,2013,2977,1000 personnes
3,1,Arménie,2515,Seigle,vegetal,1.0,NaN,1.0,0.12,0.00,...,0.0,0.0,1.0,0.0,NaN,0.0,Arménie,2013,2977,1000 personnes
4,1,Arménie,2516,Avoine,vegetal,4.0,NaN,2.0,0.37,0.03,...,1.0,0.0,5.0,0.0,NaN,NaN,Arménie,2013,2977,1000 personnes

In [118]:
#Déduction des valeurs en kcal

JR_AN= 365

fr_alim["Disponibilité alimentaire Kcal"] = fr_alim["Disponibilité alimentaire (Kcal/personne/jour)"] * (fr_alim["population"] * 1000) * JR_AN


#Déduction des valeurs en kg de protéine

fr_alim["Disponibilité kg de protéine"] = fr_alim["Disponibilité de protéines en quantité (g/personne/jour)"] / 1000 * (fr_alim["population"] * 1000) * JR_AN

In [119]:
fr_alim.head()

,code_pays,pays_x,Code Produit,Produit,origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),...,Production,Semences,Traitement,Variation de stock,pays_y,annee,population,unite,Disponibilité alimentaire Kcal,Disponibilité kg de protéine
0,1,Arménie,2511,Blé,vegetal,93.0,0.0,1024.0,130.60,3.60,...,312.0,30.0,10.0,-118.0,Arménie,2013,2977,1000 personnes,1.112684e+12,33163184.60
1,1,Arménie,2513,Orge,vegetal,137.0,26.0,0.0,0.00,0.00,...,189.0,14.0,7.0,0.0,Arménie,2013,2977,1000 personnes,0.000000e+00,0.00
2,1,Arménie,2514,Maïs,vegetal,96.0,NaN,0.0,0.03,NaN,...,21.0,0.0,NaN,NaN,Arménie,2013,2977,1000 personnes,0.000000e+00,10866.05
3,1,Arménie,2515,Seigle,vegetal,1.0,NaN,1.0,0.12,0.00,...,1.0,0.0,NaN,0.0,Arménie,2013,2977,1000 personnes,1.086605e+09,21732.10
4,1,Arménie,2516,Avoine,vegetal,4.0,NaN,2.0,0.37,0.03,...,5.0,0.0,NaN,NaN,Arménie,2013,2977,1000 personnes,2.173210e+09,97794.45

On a calculé grâce aux conversions d'unité la disponibilité alimentaire par pays et par produit en kcal uniquement( il faut comme enlevé le "par personne par jour" en calculant)idem pour les protéines en passant du g au kg.

----------------------------------------------------------

Question 4 : A partir de ces dernières informations, et à partir du poids de la disponibilité alimentaire (pour chaque pays et chaque produit), calculez pour chaque produit le ratio "énergie/poids", que vous donnerez en kcal/kg. Vous pouvez vérifier la cohérence de votre calcul en comparant ce ratio aux données disponibles sur internet, par exemple en cherchant la valeur calorique d'un oeuf.

In [120]:
"""Le ration énergie/poids se trouve par les données que le possède déja : nous avons déja le ratio énergie exprimé en kcal
   puis nous devons trouvé le poids, exprimé ici en kg -> Nourriture qu'il faut
   mettre aux bonnes unités afin de l'exploiter correctement et trouver le ratio énergie/poids."""

#Calcul du ratio énergie/poids en kcal/kg

fr_alim['ratio energie/poids'] = (fr_alim['Disponibilité alimentaire Kcal']) / (fr_alim['Nourriture'] * 1000000)

#Vérification avec l'oeuf

fr_alim[fr_alim['Produit'] == 'Oeufs'] [['pays_x','Nourriture','Disponibilité alimentaire Kcal','ratio energie/poids']]

,pays_x,Nourriture,Disponibilité alimentaire Kcal,ratio energie/poids
74,Arménie,35.0,4.889722e+10,1397.063571
144,Afghanistan,40.0,5.575740e+10,1393.935000
226,Albanie,40.0,5.327467e+10,1331.866750
319,Algérie,316.0,3.863948e+11,1222.768481
400,Angola,24.0,3.134912e+10,1306.213333
...,...,...,...,...
14579,Luxembourg,8.0,1.063975e+10,1329.968750
14663,Serbie,85.0,1.180315e+11,1388.606000
14747,Monténégro,7.0,9.973260e+09,1424.751429
14837,Soudan,38.0,5.542744e+10,1458.616842
14927,Chine,26417.0,3.878126e+13,1468.041758

In [121]:
#Calcul du pourcentage (%) de protéines de chaque produit(pour chaque pays).

fr_alim['ratio de protéine en %'] = round(((fr_alim['Disponibilité kg de protéine']) / (fr_alim['Nourriture'] * 1000000)) * 100,2)

#Vérification avec l'avoine

fr_alim.replace([np.inf, -np.inf], np.nan, inplace=True) 


fr_alim[fr_alim['Produit'] == 'Avoine'] [['pays_x','Nourriture','Disponibilité kg de protéine','ratio de protéine en %']]

,pays_x,Nourriture,Disponibilité kg de protéine,ratio de protéine en %
4,Arménie,1.0,97794.45,9.78
154,Albanie,0.0,34744.35,NaN
246,Algérie,0.0,0.00,NaN
338,Angola,0.0,0.00,NaN
419,Antigua-et-Barbuda,0.0,21024.00,NaN
...,...,...,...,...
14506,Luxembourg,1.0,71576.50,7.16
14591,Serbie,1.0,138860.60,13.89
14683,Monténégro,0.0,NaN,NaN
14765,Soudan,0.0,NaN,NaN
14850,Chine,215.0,15512503.65,7.22

In [122]:
for index, value in fr_alim.dtypes.items(): 
    if value == 'object':
        fr_alim[index] = fr_alim[index].fillna('')
    else:
        fr_alim[index] = fr_alim[index].fillna(0)

fr_alim[fr_alim['Produit'] == 'Avoine'] [['pays_x','Nourriture','Disponibilité kg de protéine','ratio de protéine en %']]

,pays_x,Nourriture,Disponibilité kg de protéine,ratio de protéine en %
4,Arménie,1.0,97794.45,9.78
154,Albanie,0.0,34744.35,0.00
246,Algérie,0.0,0.00,0.00
338,Angola,0.0,0.00,0.00
419,Antigua-et-Barbuda,0.0,21024.00,0.00
...,...,...,...,...
14506,Luxembourg,1.0,71576.50,7.16
14591,Serbie,1.0,138860.60,13.89
14683,Monténégro,0.0,0.00,0.00
14765,Soudan,0.0,0.00,0.00
14850,Chine,215.0,15512503.65,7.22

La valeur calorique renseignée par wikipédia est de 1470 Kcal/Kg , or la moyenne est de 1345 Kcal/Kg pour la valeur calorique de l'oeuf. Les résultats sont en concordance ici. Pareil pour le ration de protéine par produit : 10,7g de protéine par produit et nous trouvons 8.4% en kg ( après conversion des kg en g , nous obtenons un résultat similaire).

--------------------------------------------

Question 5 : Citez 5 aliments parmi les 20 aliments les plus caloriques, en utilisant le ratio énergie/poids. Étonnamment, il arrive que ce ratio soit différent en fonction du pays. Il faudra donc réaliser pour chaque aliment une moyenne sur les différents pays. Vous créerez donc une nouvelle table grâce à une agrégation. Attention à bien retirer les valeurs égales à 0 afin de ne pas fausser le calcul de la moyenne. Citez 5 aliments parmi les 20 aliments les plus riches en protéines.

In [123]:
"""Il faut d'abord sélectionnez les bonnes colonnes, faire un nettoyage des Nan/infini afin de ne pas fausser les 
   résultats. Ensuite, on trie les valeurs par ordre croissant pour saisir les 20 aliments les plus caloriques,
   puis parmis ceux-là, les 5 aliments les plus calorique ,pour les 2 ratios demandés."""

#Nettoyage des Nan et des infinis en les remplaçant par 0 (sinon le calcul ne fonctionne pas)

# 1- Infinies

fr_alim.loc[~np.isfinite(fr_alim['ratio energie/poids']),'ratio energie/poids'] = 0
fr_alim.loc[~np.isfinite(fr_alim['ratio de protéine en %']),'ratio de protéine en %'] = 0

In [124]:
# 2- NaN
fr_alim['ratio energie/poids'].fillna(0)
fr_alim['ratio de protéine en %'].fillna(0)

0        8.53
1        0.00
2        0.00
3        0.00
4        9.78
         ...
14938    0.00
14939    0.00
14940    6.82
14941    3.43
14942    0.00
Name: ratio de protéine en %, Length: 14943, dtype: float64

On a ensuite besoin de traiter uniquement les valeurs supérieurs à 0 pour ne pas fausser le calcul de la moyenne

In [125]:
# On crée un DataFrame avec des valeurs uniquement supérieures à 0 car toutes les autres fausses les résultats
fr_vingt_alim = fr_alim[fr_alim['ratio energie/poids'] > 0]
fr_vingt_alim = fr_alim.groupby('Produit').mean().reset_index() # Moyenne

In [126]:
# On créé une fonction pour appeler les différents DataFrame
def affichage(df, filtre, volume):
    df.sort_values(by=[filtre], inplace=True, ascending=False)
    return df.head(volume)

In [127]:
affichage(fr_vingt_alim,'ratio energie/poids',20)

,Produit,code_pays,Code Produit,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,...,Production,Semences,Traitement,Variation de stock,annee,population,Disponibilité alimentaire Kcal,Disponibilité kg de protéine,ratio energie/poids,ratio de protéine en %
41,Huile de Soja,127.592814,2571.0,0.065868,104.568862,65.694611,2.731198,7.423533,0.007784,251.245509,...,255.299401,0.000000,0.000000,0.287425,2013.0,41747.790419,1.259086e+12,1.779262e+05,6729.315586,0.047964
44,Huile de Tournesol,127.296296,2573.0,0.000000,20.185185,57.123457,2.360556,6.459012,0.005185,83.104938,...,84.290123,0.000000,0.006173,1.191358,2013.0,42929.283951,5.532941e+11,5.269683e+04,6477.260304,0.029938
30,Graisses Animales Crue,126.157233,2737.0,9.786164,64.591195,40.427673,2.037925,4.485660,0.044403,138.584906,...,144.018868,0.000000,1.503145,0.893082,2013.0,42432.861635,4.465906e+11,3.915521e+05,6291.077344,0.991006
32,Huil Plantes Oleif Autr,127.323529,2586.0,0.000000,27.829412,18.823529,0.807059,2.130882,0.011882,36.864706,...,25.576471,0.000000,1.988235,1.229412,2013.0,41105.370588,8.450456e+10,3.318032e+04,6102.670650,0.384765
42,Huile de Son de Riz,124.650000,2581.0,0.000000,11.900000,4.750000,0.197500,0.531000,0.000500,54.150000,...,55.750000,0.000000,0.000000,-1.650000,2013.0,202482.700000,3.563891e+11,2.320378e+04,5627.740882,0.034500
10,"Beurre, Ghee",126.157233,2740.0,0.037736,0.220126,25.635220,1.285912,2.900000,0.029623,60.830189,...,60.993711,0.000000,0.000000,0.547170,2013.0,42432.861635,4.729993e+11,3.892821e+05,5441.815523,0.515220
39,Huile de Palme,126.530120,2577.0,0.000000,211.753012,53.753012,2.231928,6.075120,0.007530,303.391566,...,322.963855,0.000000,0.018072,-8.361446,2013.0,41992.481928,8.002305e+11,8.498192e+04,5407.625044,0.082530
6,Arachides Decortiquees,128.363636,2556.0,0.006061,7.666667,21.618182,1.427879,1.796061,0.944182,179.945455,...,193.448485,7.848485,82.545455,-11.909091,2013.0,41968.333333,3.927825e+11,1.701676e+07,4536.801656,20.304182
35,Huile d'Olive,126.910180,2580.0,0.005988,1.874251,15.736527,0.651198,1.783653,0.000000,18.407186,...,21.221557,0.000000,0.000000,-3.065868,2013.0,41650.922156,1.468550e+11,0.000000e+00,4377.788811,0.000000
38,Huile de Germe de Maïs,126.516129,2582.0,0.000000,0.477419,10.683871,0.443290,1.208645,0.000968,14.677419,...,15.154839,0.000000,0.000000,0.412903,2013.0,43669.780645,1.257501e+11,2.061143e+03,4269.201036,0.009677
34,Huile d'Arachide,127.030864,2572.0,0.000000,7.111111,12.567901,0.519938,1.424259,0.000062,30.734568,...,31.234568,0.000000,0.000000,-0.203704,2013.0,42880.067901,2.082430e+11,2.501827e+02,4077.117993,0.006235
36,Huile de Coco,129.138365,2578.0,0.000000,7.685535,12.018868,0.497044,1.357170,0.002390,20.396226,...,19.955975,0.000000,0.012579,1.333333,2013.0,43372.779874,1.095361e+11,1.151727e+04,3811.907174,0.060503
79,Riz (Eq Blanchi),128.005917,2805.0,198.781065,109.248521,304.775148,30.957929,0.714379,5.914734,2814.343195,...,2931.627219,72.153846,39.875740,-94.426036,2013.0,41346.366864,8.171595e+12,1.531356e+08,3632.237165,6.990473
83,Sucre Eq Brut,128.005917,2542.0,0.532544,77.698225,255.923077,26.244911,0.000000,0.000000,998.171598,...,1060.278107,0.000000,65.041420,-21.520710,2013.0,41346.366864,3.018848e+12,0.000000e+00,3591.464871,0.000000
37,Huile de Colza&Moutarde,126.303226,2574.0,4.516129,83.283871,25.993548,1.084258,2.939935,0.003613,151.070968,...,156.632258,0.000000,0.006452,0.916129,2013.0,44580.567742,5.528170e+11,3.712102e+04,3561.296428,0.043290
33,Huile Graines de Coton,127.346405,2575.0,0.000000,6.967320,8.810458,0.367255,0.997320,0.000523,32.699346,...,33.222222,0.000000,0.000000,0.130719,2013.0,45392.601307,2.217358e+11,2.072709e+04,3543.947491,0.020261
24,Feve de Cacao,128.011834,2633.0,0.011834,1.674556,15.532544,1.234675,1.388402,0.258698,30.934911,...,27.449704,0.000000,0.349112,0.301775,2013.0,41298.331361,7.488384e+10,2.058728e+06,3237.215071,5.745444
12,Blé,128.005917,2511.0,763.769231,131.035503,549.355030,70.511243,3.097692,16.084142,3999.905325,...,4180.775148,202.017751,44.698225,-94.402367,2013.0,41346.366864,7.926388e+12,2.388667e+08,2846.637752,8.202249
40,Huile de Palmistes,128.986755,2576.0,0.000000,30.635762,5.317881,0.222649,0.605762,0.000331,43.509934,...,43.761589,0.000000,0.000000,0.225166,2013.0,45081.622517,1.130200e+11,5.728735e+03,2796.671892,0.022185
50,Légumineuses Autres,128.259036,2549.0,42.921687,4.915663,29.530120,3.153554,0.199699,1.897108,235.584337,...,234.018072,12.228916,0.000000,0.987952,2013.0,41920.180723,5.680514e+11,3.464324e+07,2621.671121,17.122470

In [128]:
fr_vingt_alim.loc[:,['Produit','code_pays','Code Produit','ratio energie/poids']]

                    Produit   code_pays  Code Produit  ratio energie/poids
41            Huile de Soja  127.592814        2571.0          6729.315586
44       Huile de Tournesol  127.296296        2573.0          6477.260304
30   Graisses Animales Crue  126.157233        2737.0          6291.077344
32  Huil Plantes Oleif Autr  127.323529        2586.0          6102.670650
42      Huile de Son de Riz  124.650000        2581.0          5627.740882
..                      ...         ...           ...                  ...
68       Plantes Aquatiques  123.503401        2775.0             7.555041
28         Graines de coton  128.985294        2559.0             0.000000
2    Alcool, non Comestible  128.516129        2659.0             0.000000
91   Viande de Anim Aquatiq   81.000000        2768.0             0.000000
55             Miscellanees  126.865854        2899.0             0.000000

[98 rows x 4 columns]

Parmi les 20 aliments les plus caloriques en utilisant le ratio énergie/poids, les 5 aliments les plus caloriques sont:

1-Huile de Soja

2-Huile de Tournesol

3-Graises Animales Crues

4-Huiles Plantes Oleil Autres

5-Huile de Son de Riz

In [129]:
affichage(fr_vingt_alim,'ratio de protéine en %',20)

,Produit,code_pays,Code Produit,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,...,Production,Semences,Traitement,Variation de stock,annee,population,Disponibilité alimentaire Kcal,Disponibilité kg de protéine,ratio energie/poids,ratio de protéine en %
6,Arachides Decortiquees,128.363636,2556.0,0.006061,7.666667,21.618182,1.427879,1.796061,0.944182,179.945455,...,193.448485,7.848485,82.545455,-11.909091,2013.0,41968.333333,3.927825e+11,1.701676e+07,4536.801656,20.304182
50,Légumineuses Autres,128.259036,2549.0,42.921687,4.915663,29.530120,3.153554,0.199699,1.897108,235.584337,...,234.018072,12.228916,0.000000,0.987952,2013.0,41920.180723,5.680514e+11,3.464324e+07,2621.671121,17.122470
0,Abats Comestible,125.227848,2736.0,6.348101,5.037975,7.860759,2.520823,0.232722,1.228228,104.670886,...,112.696203,0.000000,0.000000,0.164557,2013.0,42697.493671,1.043334e+11,1.657370e+07,1040.134907,16.242658
31,Haricots,127.853659,2546.0,16.286585,0.359756,27.097561,2.925000,0.123110,1.746341,137.487805,...,138.896341,7.469512,0.000000,1.652439,2013.0,42360.719512,3.606052e+11,2.290095e+07,2526.763006,16.104939
70,Pois,128.765823,2547.0,21.373418,0.177215,8.658228,0.926519,0.042342,0.568165,66.443038,...,73.113924,5.303797,0.000000,-3.955696,2013.0,42916.170886,1.228889e+11,8.215688e+06,2397.749907,15.540886
81,Soja,129.068323,2555.0,108.478261,3.962733,5.888199,0.655093,0.255280,0.589006,1661.074534,...,1728.944099,45.968944,1411.888199,-37.776398,2013.0,43040.118012,2.238732e+11,2.139104e+07,1172.264991,14.169255
92,Viande de Bovins,125.227848,2731.0,0.056962,0.537975,51.069620,11.245823,3.559177,4.418228,398.044304,...,411.386076,0.000000,-0.120253,0.183544,2013.0,42697.493671,6.158950e+11,5.452433e+07,1653.126887,14.056582
95,"Viande, Autre",125.227848,2735.0,0.360759,0.094937,5.949367,1.746582,0.253734,0.850127,41.462025,...,38.500000,0.000000,0.101266,0.018987,2013.0,42697.493671,4.897479e+10,7.400065e+06,829.627141,13.009114
94,Viande de Volailles,125.227848,2734.0,0.000000,6.291139,74.500000,20.435127,4.892468,7.115190,638.170886,...,654.006329,0.000000,3.000000,0.246835,2013.0,42697.493671,8.987926e+11,7.926912e+07,1302.289917,12.647658
90,Viande d'Ovins/Caprins,125.227848,2732.0,0.113924,0.227848,16.493671,2.780127,1.341013,1.033734,81.196203,...,82.322785,0.000000,0.000000,0.000000,2013.0,42697.493671,1.663399e+11,1.111815e+07,1711.524647,11.977215
73,Poissons Pelagiques,126.121019,2763.0,116.350318,2.292994,15.605096,6.188662,0.725414,2.087834,247.503185,...,214.566879,0.923567,0.000000,-6.815287,2013.0,42775.433121,1.242510e+11,1.720404e+07,835.701017,11.628025
58,Oeufs,126.157233,2744.0,0.459119,5.402516,26.333333,6.953019,1.835409,2.055849,439.962264,...,441.490566,29.421384,0.000000,0.100629,2013.0,42432.861635,5.511337e+11,4.289584e+07,1300.510923,10.200063
93,Viande de Suides,126.064103,2733.0,0.000000,1.801282,85.217949,13.882821,7.600256,3.861090,706.602564,...,714.128205,0.000000,0.230769,0.262821,2013.0,43027.455128,1.989371e+12,7.444209e+07,2196.129729,9.144551
71,Poissons Eau Douce,126.157233,2761.0,3.333333,16.000000,5.924528,3.251698,0.219623,0.936541,321.849057,...,325.289308,0.754717,0.000000,0.754717,2013.0,42432.861635,2.060691e+11,3.240765e+07,520.481304,8.887107
72,"Poissons Marins, Autres",125.333333,2764.0,8.826923,0.833333,4.551282,2.472436,0.152051,0.729808,61.685897,...,65.814103,0.032051,0.000000,0.006410,2013.0,42893.179487,3.735274e+10,5.849042e+06,505.244414,8.855577
12,Blé,128.005917,2511.0,763.769231,131.035503,549.355030,70.511243,3.097692,16.084142,3999.905325,...,4180.775148,202.017751,44.698225,-94.402367,2013.0,41346.366864,7.926388e+12,2.388667e+08,2846.637752,8.202249
3,Aliments pour enfants,127.638554,2680.0,0.000000,0.000000,3.620482,0.361747,0.028072,0.150843,0.500000,...,0.000000,0.000000,0.000000,0.048193,2013.0,41832.777108,1.658378e+10,7.014784e+05,1770.110422,8.122349
87,Sésame,127.382166,2561.0,0.019108,0.401274,4.636943,0.295287,0.406879,0.144268,27.025478,...,29.515924,0.490446,15.872611,-2.687898,2013.0,44271.165605,5.108388e+10,1.600254e+06,2483.601075,7.964777
97,"Épices, Autres",127.574850,2645.0,0.000000,1.107784,5.892216,0.621617,0.220240,0.182036,32.131737,...,32.760479,0.000000,0.000000,-0.065868,2013.0,41612.473054,1.001463e+11,3.277646e+06,2278.777537,7.498683
79,Riz (Eq Blanchi),128.005917,2805.0,198.781065,109.248521,304.775148,30.957929,0.714379,5.914734,2814.343195,...,2931.627219,72.153846,39.875740,-94.426036,2013.0,41346.366864,8.171595e+12,1.531356e+08,3632.237165,6.990473

In [130]:
fr_vingt_alim.loc[:,['Produit','code_pays','Code Produit','ratio de protéine en %']]

                   Produit   code_pays  Code Produit  ratio de protéine en %
6   Arachides Decortiquees  128.363636        2556.0               20.304182
50     Légumineuses Autres  128.259036        2549.0               17.122470
0         Abats Comestible  125.227848        2736.0               16.242658
31                Haricots  127.853659        2546.0               16.104939
70                    Pois  128.765823        2547.0               15.540886
..                     ...         ...           ...                     ...
43         Huile de Sésame  127.952703        2579.0                0.000000
28        Graines de coton  128.985294        2559.0                0.000000
2   Alcool, non Comestible  128.516129        2659.0                0.000000
91  Viande de Anim Aquatiq   81.000000        2768.0                0.000000
55            Miscellanees  126.865854        2899.0                0.000000

[98 rows x 4 columns]

Parmi les 20 aliments les plus riches en protéines, les 5 aliments les plus riches en protéines sont :

1-Arachides décortiquées

2-Légumineuses Autres

3-Abats Comestibles

4-Haricots

5-Poids

-------------------------------------------------------------------

Question 6 : Calculez, pour les produits végétaux uniquement, la disponibilité intérieure mondiale exprimée en kcal.

On crée un DataFrame qui ne comporte que les produits végétaux

In [131]:
fr_vegetal = fr_alim[fr_alim['origine'] == 'vegetal'].copy()
fr_vegetal.head()

,code_pays,pays_x,Code Produit,Produit,origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),...,Traitement,Variation de stock,pays_y,annee,population,unite,Disponibilité alimentaire Kcal,Disponibilité kg de protéine,ratio energie/poids,ratio de protéine en %
0,1,Arménie,2511,Blé,vegetal,93.0,0.0,1024.0,130.60,3.60,...,10.0,-118.0,Arménie,2013,2977,1000 personnes,1.112684e+12,33163184.60,2860.368946,8.53
1,1,Arménie,2513,Orge,vegetal,137.0,26.0,0.0,0.00,0.00,...,7.0,0.0,Arménie,2013,2977,1000 personnes,0.000000e+00,0.00,0.000000,0.00
2,1,Arménie,2514,Maïs,vegetal,96.0,0.0,0.0,0.03,0.00,...,0.0,0.0,Arménie,2013,2977,1000 personnes,0.000000e+00,10866.05,0.000000,0.00
3,1,Arménie,2515,Seigle,vegetal,1.0,0.0,1.0,0.12,0.00,...,0.0,0.0,Arménie,2013,2977,1000 personnes,1.086605e+09,21732.10,0.000000,0.00
4,1,Arménie,2516,Avoine,vegetal,4.0,0.0,2.0,0.37,0.03,...,0.0,0.0,Arménie,2013,2977,1000 personnes,2.173210e+09,97794.45,2173.210000,9.78

On calcul en Kcal la disponibilité intérieure : Elle est en milliers de tonne donc on la convertit en Kg afin de pouvoir faire un produit en croix avec le ratio energie/poids en Kcal/Kg afin d'obtenir la valeur uniquement en Kcal.Pareil pour la disponibilité intérieure en kg de protéine.

In [132]:
fr_vegetal['Disponibilité intérieure Kcal'] = ((fr_vegetal['Disponibilité intérieure']* 1000000) * fr_vegetal['ratio energie/poids'])

#Pour la suite des questions , la 7 en l'occurence, on aura besoin de cette colonne en kg de protéines.

fr_vegetal['Disponibilité intérieure kg de protéine'] = ((fr_vegetal['Disponibilité intérieure']* 1000000) * (fr_vegetal['ratio de protéine en %']/100))

dispo_int_produits_veg = fr_vegetal.groupby('Produit').sum().reset_index() # Aggrégation pour visualiser le résultat mondial par produit

In [133]:
# Résultats final
dispo_int_mondial_kcal = dispo_int_produits_veg['Disponibilité intérieure Kcal'].sum()
dispo_int_mondial_kcal

1.2291613356991724e+16

In [134]:
print('La disponibilité intérieure Mondiale de l\'ensemble des végétaux est donc de',
      '{:,}'.format(int(dispo_int_mondial_kcal)).replace(',', ' '),
      'Kcal.')

La disponibilité intérieure Mondiale de l'ensemble des végétaux est donc de 12 291 613 356 991 724 Kcal.

--------------------------------------------------------------------------------------

Question 7 : Combien d'humains pourraient être nourris si toute la disponibilité intérieure mondiale de produits végétaux était utilisée pour de la nourriture ? Donnez les résultats en termes de calories, puis de protéines, et exprimez ensuite ces 2 résultats en pourcentage de la population mondiale.

Le besoin calorique moyen d'un individu (homme et femme) est d'environ 2500Kcal et le besoin moyen en protéine d'un individu est d'environ 45g.

On commence d'abord par donner le résultat en calories , puis en protéines pour exprimer le résultat en % de la population. Pour un individu dans le monde, on accepte le fait que les constantes en kcal et en protéine soit vrai.

Apjrm = Apport journalier moyen par an pour désigner 1 individu

Calcul du nombre d'être humains pouvant être nourris avec cette disponibilité intérieure

In [135]:
Apjrm = 2500 
Apjrm_an = Apjrm * 365

population_nourrie_kcal = dispo_int_mondial_kcal /Apjrm_an 

print('Soit','{}'.format(int(population_nourrie_kcal)),'pouvant être nourries en kcal par cette disponibilité intérieure')

Soit 13470261213 pouvant être nourries en kcal par cette disponibilité intérieure

Donc en pourcentage de la population mondiale

In [136]:
print('Soit',((population_nourrie_kcal/(population_2013))*100),'% de la population mondiale pouvant être nourrie.')

Soit 192.50584027586558 % de la population mondiale pouvant être nourrie.

Calcul de la disponibilité intérieure mondial en Kg de protéine

In [137]:
dispo_int_mondial_kgprot = dispo_int_produits_veg['Disponibilité intérieure kg de protéine'].sum()
print('La disponibilité intérieure mondiale de l\'ensemble des végétaux est donc de',
      '{:,}'.format(int(dispo_int_mondial_kgprot)).replace(',', ' '),
      'Kg de protéine.')

La disponibilité intérieure mondiale de l'ensemble des végétaux est donc de 289 479 188 100 Kg de protéine.

Calcul du nombre de personnes pouvant être nourries avec cette disponibilité intérieure

In [138]:
AJM_prot_an =  (45/1000) * 365

# Donc en pourcentage de la population mondiale

population_nourrie_kgprot = dispo_int_mondial_kgprot/AJM_prot_an 
print('Soit','{}'.format(int(population_nourrie_kgprot)),'pouvant être nourries en kg de protéine avec cette disponibilité intérieure.')
print('Soit','{}'.format(int(population_nourrie_kgprot/population_2013)*100),'% de la population mondiale en 2013')

Soit 17624303689 pouvant être nourries en kg de protéine avec cette disponibilité intérieure.
Soit 200 % de la population mondiale en 2013

---------------------------------------------------------------------------

Question 8 : Combien d'humains pourraient être nourris si toute la disponibilité alimentaire en produits végétaux la nourriture végétale destinée aux animaux et les pertes de produits végétaux étaient utilisés pour de la nourriture ? Donnez les résultats en termes de calories, puis de protéines, et exprimez ensuite ces 2 résultats en pourcentage de la population mondiale.

Création d'une fonction pour répondre plus vite aux questions similaires à la Q7 : en terme de Kcal, Kg de protéine et le résultat en pourcentage de la population mondiale

In [139]:
def calculs_populations (donnee_kcal, donnee_kg_prot):
    disp_ajr_energetique_an = 2500 * 365
    disp_ajr_proteines_an = (45/1000)*365
    
    disp_pop_nourrie_kcal = (donnee_kcal / disp_ajr_energetique_an)
    disp_pop_nourrie_prot_kg = (donnee_kg_prot / disp_ajr_proteines_an)
    
    print_calc_pop = pd.DataFrame({'Nombre d\'habitants nourris' : [disp_pop_nourrie_kcal, disp_pop_nourrie_prot_kg],
                         '% de la population nourris' : [(disp_pop_nourrie_kcal / population_2013)*100, 
                                                (disp_pop_nourrie_prot_kg / population_2013)*100]},
                        index = ['Basé dur la dispo en Kcal', 'Basé dur la dispo en Kg de protéines'])
    return print_calc_pop

On ajoute 2 colonnes au DataFrame fr_vegetal afin de répondre à la question.

In [140]:
fr_vegetal['Dispo Alimentaire q8 (Kcal)'] = ((fr_vegetal['Disponibilité alimentaire Kcal'])
                                                               + ((fr_vegetal['Aliments pour animaux'] * 1000000) 
                                                                  * fr_vegetal['ratio energie/poids'])
                                                               + ((fr_vegetal['Pertes'] * 1000000) 
                                                                  * fr_vegetal['ratio energie/poids'])
                                                              )

fr_vegetal['Dispo Alimentaire Kg protéine q8'] = (fr_vegetal['Disponibilité kg de protéine']
                                                                      +  (((fr_vegetal['Aliments pour animaux'] 
                                                                         + fr_vegetal['Pertes']) * 1000000)
                                                                       * (fr_vegetal['ratio de protéine en %']/100))
                                                                      
                                                                        )

Agrégat sur produit avec un groupby pour avoir des résultats au niveau mondial

In [141]:
dispo_alim_vegetaux_produits = fr_vegetal.groupby(by = 'Produit').sum().reset_index()

fr_vegetal.head()

,code_pays,pays_x,Code Produit,Produit,origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),...,population,unite,Disponibilité alimentaire Kcal,Disponibilité kg de protéine,ratio energie/poids,ratio de protéine en %,Disponibilité intérieure Kcal,Disponibilité intérieure kg de protéine,Dispo Alimentaire q8 (Kcal),Dispo Alimentaire Kg protéine q8
0,1,Arménie,2511,Blé,vegetal,93.0,0.0,1024.0,130.60,3.60,...,2977,1000 personnes,1.112684e+12,33163184.60,2860.368946,8.53,1.584644e+12,47256200.0,1.470230e+12,43825684.60
1,1,Arménie,2513,Orge,vegetal,137.0,26.0,0.0,0.00,0.00,...,2977,1000 personnes,0.000000e+00,0.00,0.000000,0.00,0.000000e+00,0.0,0.000000e+00,0.00
2,1,Arménie,2514,Maïs,vegetal,96.0,0.0,0.0,0.03,0.00,...,2977,1000 personnes,0.000000e+00,10866.05,0.000000,0.00,0.000000e+00,0.0,0.000000e+00,10866.05
3,1,Arménie,2515,Seigle,vegetal,1.0,0.0,1.0,0.12,0.00,...,2977,1000 personnes,1.086605e+09,21732.10,0.000000,0.00,0.000000e+00,0.0,1.086605e+09,21732.10
4,1,Arménie,2516,Avoine,vegetal,4.0,0.0,2.0,0.37,0.03,...,2977,1000 personnes,2.173210e+09,97794.45,2173.210000,9.78,1.303926e+10,586800.0,1.086605e+10,488994.45

On calcul les sommes au niveau mondial

In [142]:
dispo_alim_mondial_vegetaux_kcal = dispo_alim_vegetaux_produits['Dispo Alimentaire q8 (Kcal)'].sum()
dispo_alim_mondial_vegetaux_kgprot = dispo_alim_vegetaux_produits['Dispo Alimentaire Kg protéine q8'].sum()

In [143]:
# Appel de la fonction pour obtenir les résultats

calculs_populations(dispo_alim_mondial_vegetaux_kcal,dispo_alim_mondial_vegetaux_kgprot)

,Nombre d'habitants nourris,% de la population nourris
Basé dur la dispo en Kcal,1.004049e+10,143.490422
Basé dur la dispo en Kg de protéines,1.237605e+10,176.868302

6 733 992 000 personnes pouvant être nourris avec cette disponibilité étendue en Kcal, soit 96.2 % de la population mondiale en 2013.

9 773 233 000 pouvant être nourris avec cette disponibilité étendue en kg de protéines, soit 139.7 % de la population mondiale en 2013.

-----------------------------------------------------------------------

Question 9 : Combien d'humains pourraient être nourris avec la disponibilité alimentaire mondiale ? Donnez les résultats en termes de calories, puis de protéines, et exprimez ensuite ces 2 résultats en pourcentage de la population mondiale.

In [144]:
# Sommes des disponibilités alimentaires dans les 2 unitées pour animaux et végétaux

dispo_alimentaire_mondiale_globale_kcal = fr_alim['Disponibilité alimentaire Kcal'].sum()
dispo_alimentaire_mondiale_globale_prot_kg = fr_alim['Disponibilité kg de protéine'].sum()

# Appel à la fonction pour affichage des résultats
calculs_populations(dispo_alimentaire_mondiale_globale_kcal,dispo_alimentaire_mondiale_globale_prot_kg)

,Nombre d'habitants nourris,% de la population nourris
Basé dur la dispo en Kcal,8.010959e+09,114.485999
Basé dur la dispo en Kg de protéines,1.241755e+10,177.461345

8 010 959 000 pouvant être nourris avec cette disponibilité alimentaire mondiale en Kcal, soit 114.5 % de la population en 2013.

12 241 775 000 pouvant être nourris avec cette disponibilité alimentaire mondiale en Kg de protéines, soit 136.21 % de la population en 2013.

-----------------------------------------------------------------------------

Question 10 : A partir des données téléchargées qui concernent la sous-nutrition, répondez à cette question : Quelle proportion de la population mondiale est considérée comme étant en sous-nutrition ?

In [145]:
# On supprime du DataFrame les valeurs des Provinces de Chine pour éviter les doublons (cf Question 1)
frsousalimentation.drop(frsousalimentation[frsousalimentation.Zone.str.startswith("Chine,") == True].index, inplace=True)
frsousalimentation.drop(frsousalimentation[frsousalimentation.Zone.str.startswith("Chine -") == True].index, inplace=True)

In [146]:
frsousalimentation['Valeur'] = pd.to_numeric(frsousalimentation['Valeur'], errors='coerce')

In [147]:
frsousalimentation['Année'] = pd.to_numeric(frsousalimentation['Année'].str[0:4])+1

In [148]:
frsousalimentation = pd.DataFrame(frsousalimentation)

In [149]:
frsousalimentation_sou = frsousalimentation[frsousalimentation['Année'] == 2013].copy()
frsousalimentation_sou['Valeur'] = frsousalimentation_sou['Valeur'] * 1000000 

pers_sous_nutrition = round(frsousalimentation_sou['Valeur'].sum())
pers_sous_nutrition_pourcent = round((pers_sous_nutrition * 100)/population_2013,3)

print('Il y a',pers_sous_nutrition,'personnes sous nutries dans le monde')
print('Il y a , en pourcentage',pers_sous_nutrition_pourcent,'%' ,'de personnes en sous nutrition dans le monde.')

Il y a 743800000 personnes sous nutries dans le monde
Il y a , en pourcentage 10.63 % de personnes en sous nutrition dans le monde.

---------------------------------------------------------------------------------------

Question 11 : En ne prenant en compte que les céréales destinées à l'alimentation (humaine et animale), quelle proportion (en termes de poids) est destinée à l'alimentation animale ?

Établissez la liste des produits (ainsi que leur code) considéré comme des céréales selon la FAO.

Repérez dans vos données les informations concernant les céréales (par exemple en créant une colonne de type booléen nommée "is_cereal").

In [150]:
# Création d'une liste contenant toutes les céréales

list_cereale = pd.Series(frcéréales['Produit'].unique())
list_cereale

0                 Blé
1    Riz (Eq Blanchi)
2                Orge
3                Maïs
4              Millet
5              Seigle
6              Avoine
7              Sorgho
8    Céréales, Autres
dtype: object

In [151]:
# Mise en place de la colonne is_cereal

fr_alim['is_cereal'] = fr_alim['Produit'].isin(list_cereale)
fr_alim['code_cereal'] = frcéréales['Code Produit']
fr_alim.head()

,code_pays,pays_x,Code Produit,Produit,origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),...,pays_y,annee,population,unite,Disponibilité alimentaire Kcal,Disponibilité kg de protéine,ratio energie/poids,ratio de protéine en %,is_cereal,code_cereal
0,1,Arménie,2511,Blé,vegetal,93.0,0.0,1024.0,130.60,3.60,...,Arménie,2013,2977,1000 personnes,1.112684e+12,33163184.60,2860.368946,8.53,True,2511.0
1,1,Arménie,2513,Orge,vegetal,137.0,26.0,0.0,0.00,0.00,...,Arménie,2013,2977,1000 personnes,0.000000e+00,0.00,0.000000,0.00,True,2805.0
2,1,Arménie,2514,Maïs,vegetal,96.0,0.0,0.0,0.03,0.00,...,Arménie,2013,2977,1000 personnes,0.000000e+00,10866.05,0.000000,0.00,True,2513.0
3,1,Arménie,2515,Seigle,vegetal,1.0,0.0,1.0,0.12,0.00,...,Arménie,2013,2977,1000 personnes,1.086605e+09,21732.10,0.000000,0.00,True,2514.0
4,1,Arménie,2516,Avoine,vegetal,4.0,0.0,2.0,0.37,0.03,...,Arménie,2013,2977,1000 personnes,2.173210e+09,97794.45,2173.210000,9.78,True,2517.0

In [152]:
# Calcul du poids des aliments humain et nourriture animale 
part_cereales_animales = fr_alim[fr_alim['is_cereal'] == True]['Aliments pour animaux'].sum() 
part_nourriture_humaine = fr_alim[fr_alim['is_cereal'] == True]['Nourriture'].sum()

# Calcul du taux de nourriture animale
taux_nourriture_animale = (part_cereales_animales / (part_cereales_animales + part_nourriture_humaine))*100
print('La part de nourriture animale sur la part globale de céréales à destination humaine et animale est de',
      round(taux_nourriture_animale,2), '%')

La part de nourriture animale sur la part globale de céréales à destination humaine et animale est de 45.93 %

------------------------------------------------------------------------------

Question 12 : Donnez les 3 produits qui ont la plus grande valeur pour chacun des 2 ratios (vous aurez donc 6 produits à citer)

Sélectionnez parmi les données des bilans alimentaires les informations relatives aux pays dans lesquels la FAO recense des personnes en sous-nutrition.

Repérez les 15 produits les plus exportés par ce groupe de pays.

Parmi les données des bilans alimentaires au niveau mondial, sélectionnez les 200 plus grandes importations de ces produits (1 importation = une quantité d'un produit donné importée par un pays donné)

Groupez ces importations par produit, afin d'avoir une table contenant 1 ligne pour chacun des 15 produits. Ensuite, calculez pour chaque produit les 2 quantités suivantes :

le ratio entre la quantité destinés aux "Autres utilisations" (Other uses) et la disponibilité intérieure. le ratio entre la quantité destinée à la nourriture animale et la quantité destinée à la nourriture (animale + humaine)

In [153]:
for var in fr_alim[['Production',
 'Importations - Quantité',
 'Variation de stock',
 'Exportations - Quantité',
 'Disponibilité intérieure',
 'Aliments pour animaux',
 'Semences',
 'Pertes',
 'Traitement',
 'Autres utilisations (non alimentaire)',
 'Nourriture']]:
    fr_alim[var] *= 1000000

In [154]:
# On fait un repérage dans le Df fr_alim pour les pays en sous nutrition via une liste.
pays_sous_nutri = frsousalimentation.loc[frsousalimentation['Valeur'] > 0,'Zone'].unique()
fr_alim['Présence sous nutrition'] = fr_alim['pays_x'].isin(pays_sous_nutri)

In [155]:
# On cherche les 15 plus grandes exportations pour ces pays là.
exporte = fr_alim[fr_alim['Présence sous nutrition'] == True]
pdt_export_top = exporte.groupby('Produit')['Exportations - Quantité'].sum().sort_values(ascending=False).reset_index()[:15]
pdt_export_top

                Produit  Exportations - Quantité
0                  Maïs             5.470400e+10
1        Huile de Palme             4.632200e+10
2                Manioc             3.592300e+10
3                   Blé             3.333100e+10
4      Riz (Eq Blanchi)             3.282700e+10
5         Sucre Eq Brut             2.552700e+10
6       Légumes, Autres             2.011800e+10
7               Bananes             1.783000e+10
8                  Soja             1.590100e+10
9        Fruits, Autres             1.543000e+10
10   Lait - Excl Beurre             1.458900e+10
11  Poissons Pelagiques             1.249700e+10
12              Tomates             9.107000e+09
13                 Orge             8.779000e+09
14               Pommes             8.385000e+09

In [156]:
# On va sélectionner les 200 plus grandes Importatations en quantités parmis ces 15 produits les plus exportés.

list_produit = ['Maïs','Huile de Palme','Manioc','Blé','Riz(Eq Blanchi)','Sucre Eq Brut','Légumes,Autres','Bananes','Soja','Lait - Excl Beurre','Fruits,Autres','Poissons Pelagiques','Tomates','Orge','Pommes']
# tempo = Variable temporaire

tempo = exporte.loc[exporte['Produit'].isin(list_produit), :]
tempo = tempo.sort_values('Importations - Quantité',ascending=False)[:200]


prod_group = tempo.groupby('Produit').sum()

# Calculs des ratios

prod_group['ratio 1'] = prod_group['Autres utilisations (non alimentaire)'] / prod_group['Disponibilité intérieure']
prod_group['ratio 2'] = prod_group['Aliments pour animaux']/(prod_group['Aliments pour animaux'] + prod_group['Nourriture'])

prod_group[['ratio 1','ratio 2']]

                      ratio 1   ratio 2
Produit
Bananes              0.001574  0.000000
Blé                  0.033634  0.168576
Huile de Palme       0.670951  0.000000
Lait - Excl Beurre   0.008005  0.046784
Manioc               0.317715  0.621443
Maïs                 0.119649  0.806284
Orge                 0.000287  0.952803
Poissons Pelagiques  0.002260  0.642202
Pommes               0.000078  0.000000
Soja                 0.005815  0.619296
Sucre Eq Brut        0.046157  0.000325
Tomates              0.008385  0.000000

In [157]:
# Les 3 produits pour les 2 ratios

Ratio1 = prod_group.groupby('Produit').sum()[['ratio 1']].sort_values(by=['ratio 1'],ascending=False).head(3)
Ratio2 = prod_group.groupby('Produit').sum()[['ratio 2']].sort_values(by=['ratio 2'],ascending=False).head(3)

print(Ratio1,'=> Rapport Autres utilisations par la Disponibilité intérieure')
print(Ratio2,'=> Rapport  entre la quantité destinée à la nourriture animale et la quantité destinée à la nourriture (animale + humaine)')

                 ratio 1
Produit
Huile de Palme  0.670951
Manioc          0.317715
Maïs            0.119649 => Rapport Autres utilisations par la Disponibilité intérieure
                      ratio 2
Produit
Orge                 0.952803
Maïs                 0.806284
Poissons Pelagiques  0.642202 => Rapport  entre la quantité destinée à la nourriture animale et la quantité destinée à la nourriture (animale + humaine)

------------------------------------------------------------------------------------

Question 13 : Combien de tonnes de céréales pourraient être libérées si les USA diminuaient leur production de produits animaux de 10% ?

In [158]:
cereal_animaux_usa = fr_alim[(fr_alim['is_cereal'] == True) 
                                                 & (fr_alim['pays_x'] == 'États-Unis d\'Amérique')]['Aliments pour animaux'].sum()
print('{}'.format(int((cereal_animaux_usa))*0.1),'de tonnes de céréales pourraient être libérées si les USA diminuaient leur production de produits animaux de 10%')

14009600000.0 de tonnes de céréales pourraient être libérées si les USA diminuaient leur production de produits animaux de 10%

------------------------------------------------------------------------------------------------------------

Question 14 : En Thaïlande, quelle proportion de manioc est exportée ? Quelle est la proportion de personnes en sous-nutrition?

In [159]:
# On sélectionne d'abord les données générales -> le pays et le produit en question.
prop_manioc_thailande =  fr_alim[(fr_alim['pays_x'] == 'Thaïlande') & (fr_alim['Produit'] == 'Manioc')]

# Ensuite , on demande la propotion de manioc exportée -> appel à la colonne Exportations-Quantité

thailande_manioc_exportes = (prop_manioc_thailande['Exportations - Quantité'] / (prop_manioc_thailande['Disponibilité intérieure']+prop_manioc_thailande['Exportations - Quantité']))*100

print(thailande_manioc_exportes)
print('La thaïlande exporte 80% de son manioc en 2013')

12599    80.100388
dtype: float64
La thaïlande exporte 80% de son manioc en 2013

In [160]:
prop_manioc_thailande.head()

,code_pays,pays_x,Code Produit,Produit,origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),...,annee,population,unite,Disponibilité alimentaire Kcal,Disponibilité kg de protéine,ratio energie/poids,ratio de protéine en %,is_cereal,code_cereal,Présence sous nutrition
12599,216,Thaïlande,2532,Manioc,vegetal,1.800000e+09,2.081000e+09,40.0,13.0,0.05,...,2013,67011,1000 personnes,9.783606e+11,3424262.1,1123.261309,0.39,False,NaN,True

In [161]:
# Proportion de personnes en sous nutrition

pro_sous_nutri_thailande = (float(frsousalimentation_sou[frsousalimentation_sou['Zone'] == 'Thaïlande']['Année'])
                            / float(prop_manioc_thailande['population']))*100

In [162]:
print(pro_sous_nutri_thailande,'% de la population en Thaïlande est sous nutrie.')

3.003984420468281 % de la population en Thaïlande est sous nutrie.

-----------------------------------------------------------------------------------------

---------------------------------------------------------------------------------------------

# Exportation des DataFrames vers les tables MySQL/SQLite

Transformez vos données en un format propice à l’utilisation souhaitée par les utilisateurs finaux, qui utiliserons votre base via le langage SQL. Une fois les données correctement formatées, vous les intégrerez dans une base de données.

In [76]:
# Exportation de df frpopulation

# Suppression des doublons de Chine

def suppr_chine(fc_dataframe):
    fc_dataframe.drop(fc_dataframe[fc_dataframe.Zone.str.startswith("Chine,") == True].index, inplace=True)
    fc_dataframe.drop(fc_dataframe[fc_dataframe.Zone.str.startswith("Chine -") == True].index, inplace=True)
    
    return print('Supression des provinces de Chine effectuée')

In [77]:
frpopulation.head()

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
0,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,511,Population totale,2501,Population,2013,2013,1000 personnes,30552,NaN,Donnée officielle
1,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,202,Afrique du Sud,511,Population totale,2501,Population,2013,2013,1000 personnes,52776,NaN,Donnée officielle
2,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,3,Albanie,511,Population totale,2501,Population,2013,2013,1000 personnes,3173,NaN,Donnée officielle
3,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,4,Algérie,511,Population totale,2501,Population,2013,2013,1000 personnes,39208,NaN,Donnée officielle
4,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,79,Allemagne,511,Population totale,2501,Population,2013,2013,1000 personnes,82727,NaN,Donnée officielle

In [78]:
# DataFrame Population 

suppr_chine(frpopulation)

Supression des provinces de Chine effectuée

In [79]:
frpopulation_exprt = frpopulation[['Zone','Code zone','Année','Valeur']].copy()
frpopulation_exprt['Valeur'] = frpopulation_exprt['Valeur'] * 1000
frpopulation_exprt = frpopulation_exprt.rename(columns = {'Zone':'pays','Code zone':'code_pays','Année':'annee','Valeur':'population'})

frpopulation_exprt.to_csv("population.csv",index = False)

In [80]:
fr_alim.head()

,code_pays,pays_x,Code Produit,Produit,origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),...,annee,population,unite,Disponibilité alimentaire Kcal,Disponibilité kg de protéine,ratio energie/poids,ratio de protéine en %,is_cereal,code_cereal,Présence sous nutrition
0,1,Arménie,2511,Blé,vegetal,93000000.0,0.0,1024.0,130.60,3.60,...,2013,2977,1000 personnes,1.112684e+12,33163184.60,2860.368946,8.53,True,2511.0,True
1,1,Arménie,2513,Orge,vegetal,137000000.0,26000000.0,0.0,0.00,0.00,...,2013,2977,1000 personnes,0.000000e+00,0.00,0.000000,0.00,True,2805.0,True
2,1,Arménie,2514,Maïs,vegetal,96000000.0,0.0,0.0,0.03,0.00,...,2013,2977,1000 personnes,0.000000e+00,10866.05,0.000000,0.00,True,2513.0,True
3,1,Arménie,2515,Seigle,vegetal,1000000.0,0.0,1.0,0.12,0.00,...,2013,2977,1000 personnes,1.086605e+09,21732.10,0.000000,0.00,True,2514.0,True
4,1,Arménie,2516,Avoine,vegetal,4000000.0,0.0,2.0,0.37,0.03,...,2013,2977,1000 personnes,2.173210e+09,97794.45,2173.210000,9.78,True,2517.0,True

In [81]:
# DataFrame dispo_alim 

dispo_alim_export = fr_alim[['pays_x','code_pays','annee','Produit', 'Code Produit', 'origine', 'population', 'Disponibilité alimentaire en quantité (kg/personne/an)', 'Disponibilité alimentaire (Kcal/personne/jour)',
                                             'Disponibilité de protéines en quantité (g/personne/jour)', 'Disponibilité de matière grasse en quantité (g/personne/jour)']].copy()
# Calcul de la dispo alimentaire en Tonnes
dispo_alim_export['Disponibilité alimentaire en quantité (kg/personne/an)'] = ((dispo_alim_export['Disponibilité alimentaire en quantité (kg/personne/an)']
                                                                                 * (dispo_alim_export['population']*1000) * 365)/1000)
dispo_alim_export.drop('population', axis='columns', inplace=True)
dispo_alim_export = dispo_alim_export.rename(columns = {'pays_x':'pays','Produit':'produit', 'Code Produit':'code_produit', 
                                       'origine':'origin', 'Disponibilité alimentaire en quantité (kg/personne/an)':'dispo_alim_tonnes', 
                                       'Disponibilité alimentaire (Kcal/personne/jour)':'dispo_alim_kcal_p_jr', 
                                       'Disponibilité de protéines en quantité (g/personne/jour)':'dispo_prot', 
                                       'Disponibilité de matière grasse en quantité (g/personne/jour)':'dispo_mat_gr'})
dispo_alim_export.to_csv('dispo_alim.csv', index=False)

In [82]:
# DataFrame equilibre_prod

equilibre_prod_export = fr_alim[['pays_x','code_pays','annee','Produit','Code Produit', 'Disponibilité intérieure',
                                                'Aliments pour animaux', 'Semences', 'Pertes', 'Traitement', 'Nourriture', 
                                                 'Autres utilisations (non alimentaire)']]

equilibre_prod_export = equilibre_prod_export.rename(columns = {'pays_x':'pays', 'Produit':'produit',
                                                                      'Code Produit':'code_produit', 'Disponibilité intérieure':'dispo_int',
                                                                      'Aliments pour animaux':'alim_ani', 'Semences':'semences', 'Pertes':'pertes',
                                                                      'Traitement':'transfo', 'Nourriture':'nourriture', 
                                                                      'Autres utilisations (non alimentaire)':'autres_utilisations'})

# Conversion des unités "Millier de tonnes" en Tonnes
equilibre_prod_export.loc[:, ['dispo_int', 'alim_ani', 'semences', 'pertes', 'transfo', 'nourriture','autres_utilisations']]*=1000

In [83]:
equilibre_prod_export.to_csv('equilibre_prod.csv',index=False)

In [84]:
equilibre_prod_export

,pays,code_pays,annee,produit,code_produit,dispo_int,alim_ani,semences,pertes,transfo,nourriture,autres_utilisations
0,Arménie,1,2013,Blé,2511,5.540000e+11,9.300000e+10,3.000000e+10,3.200000e+10,1.000000e+10,3.890000e+11,0.000000e+00
1,Arménie,1,2013,Orge,2513,1.980000e+11,1.370000e+11,1.400000e+10,1.500000e+10,7.000000e+09,0.000000e+00,2.600000e+10
2,Arménie,1,2013,Maïs,2514,1.020000e+11,9.600000e+10,0.000000e+00,7.000000e+09,0.000000e+00,0.000000e+00,0.000000e+00
3,Arménie,1,2013,Seigle,2515,1.000000e+09,1.000000e+09,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
4,Arménie,1,2013,Avoine,2516,6.000000e+09,4.000000e+09,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+09,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...,...
14938,Chine,351,2013,Huiles de Poissons,2781,1.270000e+11,4.700000e+10,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,8.000000e+10
14939,Chine,351,2013,Huiles de Foie de Poisso,2782,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
14940,Chine,351,2013,Riz (Eq Blanchi),2805,1.350240e+14,1.211700e+13,4.679000e+12,6.406000e+12,1.200000e+10,1.097250e+14,2.085000e+12
14941,Chine,351,2013,Lait - Excl Beurre,2848,5.011700e+13,1.632000e+12,0.000000e+00,1.433000e+12,0.000000e+00,4.700900e+13,4.200000e+10
14942,Chine,351,2013,Miscellanees,2899,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00

In [85]:
# DataFrame sous_nutrition

suppr_chine(frsousalimentation_sou)

sous_nutrition_export = frsousalimentation_sou[['Zone','Code zone','Année','Valeur']]
sous_nutrition_export = sous_nutrition_export.rename(columns = {'Zone':'pays', 'Code zone':'code_pays', 'Année':'annee','Valeur':'nb_personnes'})
sous_nutrition_export = sous_nutrition_export[['pays','code_pays','annee','nb_personnes']]

Supression des provinces de Chine effectuée

In [86]:
sous_nutrition_export = sous_nutrition_export.reset_index(drop=True)
sous_nutrition_export

                                       pays  code_pays  annee  nb_personnes
0                               Afghanistan          2   2013     7900000.0
1                            Afrique du Sud        202   2013     2600000.0
2                                   Albanie          3   2013      200000.0
3                                   Algérie          4   2013     1700000.0
4                                 Allemagne         79   2013           NaN
..                                      ...        ...    ...           ...
195  Venezuela (République bolivarienne du)        236   2013     1900000.0
196                                Viet Nam        237   2013    10400000.0
197                                   Yémen        249   2013     7200000.0
198                                  Zambie        251   2013     7000000.0
199                                Zimbabwe        181   2013     6600000.0

[200 rows x 4 columns]

In [84]:
sous_nutrition_export[sous_nutrition_export['code_pays'] > 0].to_csv('sous_nutrition.csv', index=False)